### ISSUE TITLE
CPU Spike to 40% 

### ISSUE THREAD

**Issue by weixiyen** [YuAo/Vivid#2]
Thanks for the great filter library.

When using your skin smoothing CIFilter and profiling my app, I noticed it kept jumping to 30-50% CPU on my iPhone 6s.

Here's an image of the calls causing it.

<img width="1024" alt="screenshot 2016-04-29 20 57 57" src="https://cloud.githubusercontent.com/assets/59597/14933720/29af160a-0e4d-11e6-8f11-eea922d42a07.png">

The culprit seems to be YUCIRGBToneCurve, a CIFilter subclass.

Throws this error:
[CIFilter _crashed_when_dealloc_called_setValue_nil_forKey_probably_because_the_subclass_already_released_it:]

**Comment by YuAo** [comment]
Thanks for the PR and these inputs.

Are you keep creating skin smoothing filters? You may consider reusing the filter object to improve performance.

**Comment by YuAo** [comment]
Hi @weixiyen 

The error you pointed out exists within lots of system filters.

For instance, CIBlendWithAlphaMask:
![screen shot 2016-04-30 at 22 45 58](https://cloud.githubusercontent.com/assets/1234944/14936708/160044e2-0f26-11e6-8eaa-b346016cf2cf.png)

The performance issue you noticed is actually caused by the setters of the input control points property. When a filter is destroyed, the system calls setValueForKey with nil value for all input keys of the filter. Unfortunately, every time the setter is called, the setter invalidates the curve points and recalculates the tone curve texture, which takes a a lot of time. 

I've revisited the implementation of the RGB tone curve filter, moved the texture generation from the setters to the outputImage method. The setters now only invalidate the internal values (without trying to recalculate them or regenerate the tone curve texture).

An internal cache is also added to cache the results of the curve points calculation.

You can go ahead and test these changes in your own project. Again, avoid create and destroy filters when you can reuse them.

**Comment by weixiyen** [comment]
Thanks, it's as you said, caching the filter and re-using it got rid of the issue entirely.  Thank you!
